* Ruby
** Gems
*** ruby-lint
https://github.com/YorickPeterse/ruby-lint

from the readme:
#+BEGIN_QUOTE
ruby-lint is a static code analysis tool for Ruby. It is inspired by tools such as jshint, flake8 and similar tools. ruby-lint primarily focuses on logic related errors such as the use of non existing variables instead of focusing on semantics (e.g. the amount of characters per line).
#+END_QUOTE

*** YARD
http://yardoc.org/

#+BEGIN_QUOTE
YARD is a documentation generation tool for the Ruby programming language. It enables the user to generate consistent, usable documentation that can be exported to a number of formats very easily, and also supports extending for custom Ruby constructs such as custom class level definitions.
#+END_QUOTE

*** bcrypt-ruby
https://github.com/codahale/bcrypt-ruby

#+BEGIN_QUOTE
bcrypt-ruby is a Ruby binding for the OpenBSD bcrypt() password hashing algorithm, allowing you to easily store a secure hash of your users' passwords.
#+END_QUOTE

** Resources
- http://www.zenspider.com/Languages/Ruby/QuickRef.html

* Rails
** Testing (Minitest)
*** Fixtures
http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html

If you set an ID for a fixture:
- use the ID when setting up a relation between that fixture and another fixture

  Example:
  #+BEGIN_SRC 
  # genres.yml
  fiction:
    id: 1
    name: Fiction

  # books.yml
  alice:
    title: Alice in Wonderland
    genre_id: 1
  #+END_SRC

*** Resources
Tutorials
- http://nithinbekal.com/posts/capybara-minitest-rails

Gems
- https://github.com/blowmage/minitest-rails-capybara
- https://github.com/jnicklas/capybara
- https://github.com/copiousfreetime/launchy

** User authentication
API
- http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html#method-i-has_secure_password
  - uses the bcrypt gem

** Articles
- http://billpatrianakos.me/blog/2013/10/13/list-of-rails-status-code-symbols/
  - a comment links to the [[https://github.com/rack/rack/blob/1569a985e17d9caaf94d0e97d95ef642c4ab14ba/lib/rack/utils.rb#L470][map of HTTP status codes in Rack on Github]]
- http://brandonhilkert.com/blog/7-reasons-why-im-sticking-with-minitest-and-fixtures-in-rails/
- http://culttt.com/2016/02/17/replacing-fixtures-with-factory-girl-in-ruby-on-rails/
- http://culttt.com/2016/02/10/using-form-objects-in-ruby-on-rails-with-reform/
  - includes examples of form tests
- http://everydayrails.com/2015/04/05/rspec-assigns-rails-testing.html
  - the difference between assigns and reload
  - assigns will be deprecated in Rails 5
- https://buildtoship.com/upcoming-changes-in-rails-5-0/
  - controller tests may be phased out in favor of integration tests
